{% set name = "p_astro" %}
{% set version = "0.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5331f3a9f8cc77eb9c87b3769c859844f19e532081e553b3a32bae8e6f471aa6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -v"
  entry_points:
    - em_bright_categorize = driver_scripts.categorize:main
    - em_bright_dag_writer = driver_scripts.dag_writer:main
    - em_bright_extract = driver_scripts.utils:extract
    - em_bright_join = driver_scripts.utils:join
    - em_bright_train = driver_scripts.utils:train
    - p_astro_histogram_by_bin = driver_scripts.p_astro_utils:histogram_by_bin
    - p_astro_compute_means = driver_scripts.p_astro_utils:compute_counts_mean

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools
  run:
    - astropy
    - h5py
    - ligo-common
    - numpy
    - pandas
    - python >=3.6
    - python-lal
    - python-lalinspiral
    - python-lalsimulation
    - python-ligo-lw
    - scikit-learn 0.19.2
    - scipy

test:
  imports:
    - ligo.computeDiskMass
    - ligo.em_bright
    - ligo.p_astro

about:
  home: https://lscsoft.docs.ligo.org/p-astro/
  dev_url: https://git.ligo.org/lscsoft/p-astro/
  doc_url: https://lscsoft.docs.ligo.org/p-astro/
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Low-latency estimation of category-wise astrophysical probability of GW candidates

extra:
  recipe-maintainers:
    - duncanmmacleod
