{% set name = "p_astro" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29293a33e87409dfdc970c06bf7d5756aaea72e139db7fc8f9266f2c2f2f83eb
  patches:
    - 0001-setup.py-update-requirements.patch
    - 0002-setup.py-update-namespace-package-config.patch

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - p_astro_compute_means = ligo.p_astro_utils:compute_counts_mean
    - p_astro_histogram_by_bin = ligo.p_astro_utils:histogram_by_bin

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - astropy-base
    - h5py
    - numpy
    - python >={{ python_min }}
    - python-lal
    - python-lalinspiral
    - python-lalsimulation
    - python-ligo-lw
    - scipy

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    # check dependencies
    - python -m pip check p_astro
    - python -m pip show p_astro
    # run test suite
    - python -m pytest --pyargs -ra -v ligo.tests
    # check scripts
    - p_astro_compute_means --help
    - p_astro_histogram_by_bin --help

about:
  home: https://lscsoft.docs.ligo.org/p-astro/
  dev_url: https://git.ligo.org/lscsoft/p-astro.git
  doc_url: https://lscsoft.docs.ligo.org/p-astro/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Low-latency estimation of category-wise astrophysical probability of GW candidates

extra:
  recipe-maintainers:
    - deepchatterjeeligo
    - duncanmmacleod
