{% set name = "p_astro" %}
{% set version = "0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18ce7573c148939d6d472657139be0d205a60c613c0375c61b2cd0c5e2b73855

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  entry_points:
    - em_bright_categorize = driver_scripts.categorize:main
    - em_bright_dag_writer = driver_scripts.dag_writer:main
    - em_bright_extract = driver_scripts.utils:extract
    - em_bright_join = driver_scripts.utils:join
    - em_bright_train = driver_scripts.utils:train
    - p_astro_histogram_by_bin = driver_scripts.p_astro_utils:histogram_by_bin
    - p_astro_compute_means = driver_scripts.p_astro_utils:compute_counts_mean

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools
  run:
    - astropy
    - ligo-common
    - numpy
    - pandas
    - python >=3.6
    - python-lal
    - python-lalinspiral
    - python-lalsimulation
    - scikit-learn 0.19.2
    - scipy

test:
  imports:
    - ligo.computeDiskMass
    - ligo.em_bright
    - ligo.p_astro

about:
  home: http://gracedb.ligo.org
  doc_url: https://lscsoft.docs.ligo.org/p-astro/
  license: GPLv3
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Low-latency estimation of category-wise astrophysical probability of GW candidates

extra:
  recipe-maintainers:
    - duncanmmacleod
