travis:
  secure:
    BINSTAR_TOKEN: HBbPZ12mF6iKse2e0Muv3VI3dap6lekWM7YpVGGbL+dY9LnAzpxChIKBvepm8uCVM0Hn5H34zPDI9+3wUtgcLswMHHiPWnNNgS2vncvkJEYdCNInu3qmpMW7K0LMMoOREbELIpzZFOUwZ6Dwo66RZn54pH25AyxERx+iWMgVlUQqsCKuM91VfM+8NuWjCKPXFesY01BGC1uwW9xHryL0nDHaygkvOpjXShGl7V37Gbzs86L/cLabNMJHC+L3SAZD0ArJRt6N+N81tgkEnFtPWjpTXy8/8r2j2N8JzPypFSzd2cX+CgkjaRKi/m59ym//Kf28S9gA5PSmX8q+Pn0ZYEUCHijXaEgyTS7p7W75tsb6hEtEu3NsTcboPVt+7fi58Lyvbttw9EDmrT5ukopqINqjxKH4rdqeuUsgSWxuyLmLpF5dd0HDMOrwsn32rRNxt/cDCK2errukOFPVHzlr3Y2D0mv837nD9vh6OYO3Z1BGOHz+ZmCjOQerzHCdQxhEzTpDw4HddukiGZh/6brZ2kiXIqqEP/JblhuZ/OndJyeACvGBICdogQyAqFRnXlhJ7csR7VZx4YedJmDx2Mj0b/aGcZMJXl2MRjLGEznhWL+ZjHCC5au26QWKBzZSsHgk9WRA6q6g0AoZjYVVobgV8l562n5ZUZSszbR5W94ESZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
